---
name: ci
on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron:  '30 15 * * *'
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        otp:
          - 25
          - 26
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo build
      - run: cargo test
      - name: Build
        run: make deps app dialyze tests
      - run: |
          echo MATRIX_OTP="${{matrix.otp}}" >> $GITHUB_ENV
          echo MATRIX_OS="${{matrix.os}}" >> $GITHUB_ENV
          echo ARTIFACT_NAME="ct-logs-${MATRIX_OS}-${MATRIX_OTP}" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: logs
