---
name: ci
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - run: cargo clippy
      - run: cargo build
      - run: cargo test
      - name: Build
        run: make deps app dialyze tests
