---
name: ci
on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron:  '30 15 * * *'
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        otp: ['25', '26']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo build
      - run: cargo test
      - name: Build
        run: make deps app dialyze tests
      - uses: actions/upload-artifact@v3
        with:
          name: ct-logs
          path: logs
